config/routes.rb
FoodApp::Application.routes.draw do

  root 'foods#index'

  resources:foods

end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def show
		@food = Food.find(params[:id])
	end

	def new
		@food = Food.new
		
	end

	def create
		@food = Food.create food_params
		redirect_to food_path(@food)
	end

	def edit
		@food = Food.find(params[:id])
	end

	def update 
		@food = Food.find(params[:id])
		@food.update food_params
		redirect_to food_path(@food)
	end

	def destroy
		Food.find(params[:id]).destroy
		redirect_to root_path
	end

private
def food_params
	params.require(:food).permit(:item, :description)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<h1>Edit your Food</h1>
<%= form_for @food do |f| %>

	<%= label_tag(:item, "Item:")%>
	<%= f.text_field :item %></br>

	<%= label_tag(:description, "Description") %>
	<%= f.text_area :description %></br>

	<%= f.submit "Upadte" %>
	<% end %>

app/views/foods/index.html.erb
<h1> Idex PAge! </h1>

<%= link_to "New Food Item",  new_food_path %>

<% @foods.each do |food| %>

	<li><%=link_to food.item, food_path(food.id) %>
	<%= link_to "edit", edit_food_path(food[:id]) %>
	<%= link_to "delete", food, method: :delete, date: {confirm: "You sure?"}%>
	</li>


	<% end %>

app/views/foods/new.html.erb
<h1>Create a New Food</h1>
<%= form_for @food do |f| %>

	<%= label_tag(:item, "Item") %>
	<%= f.text_field :item %> </br>

	<%= label_tag(:description, "Decription") %>
	<%= f.text_area :description %></br>
	<%= f.submit "Create" %>

	<% end %>

app/views/foods/show.html.erb
<FOOD show Page</h1>

	<p> Item: <%= @food['item']%></p>
	<p>Description: <%= @food['description']%></p>

	<%= link_to "Back to Food List",foods_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>